const colors = {
  light: {
    text: '#1a1a2e',
    tint: '#e63946',
    background: '#f8f9fa',
    foreground: '#1a1a2e',
    card: '#ffffff',
    cardForeground: '#1a1a2e',
    primary: '#e63946',
    primaryForeground: '#ffffff',
    secondary: '#1e2128',
    secondaryForeground: '#ffffff',
    muted: '#e9ecef',
    mutedForeground: '#6c757d',
    accent: '#e63946',
    accentForeground: '#ffffff',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#dee2e6',
    input: '#dee2e6',
  },
  dark: {
    text: '#f8f9fa',
    tint: '#e63946',
    background: '#12131a',
    foreground: '#f8f9fa',
    card: '#1e2128',
    cardForeground: '#f8f9fa',
    primary: '#e63946',
    primaryForeground: '#ffffff',
    secondary: '#2a2d38',
    secondaryForeground: '#f8f9fa',
    muted: '#2a2d38',
    mutedForeground: '#8f949e',
    accent: '#e63946',
    accentForeground: '#ffffff',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#2a2d38',
    input: '#2a2d38',
  },
  radius: 12,
};

export default colors;
